#!/usr/bin/env node
/**
 * Tier 3 Test Runner - Visual Regression
 *
 * Renders charts headlessly and compares against baselines.
 * Now with 22 different data scenarios per chart type.
 * No browser or Kibana required.
 */

import { chartRegistry } from '../../src/services/vega/index.js';
import { HeadlessRenderer } from './HeadlessRenderer.js';
import { BaselineManager } from './BaselineManager.js';
import { TEST_CONFIGS } from '../spec-validation/run.js';
import {
  SCENARIOS,
  generateScenarioData,
  getScenarioConfig,
  CHART_DATA_TYPES
} from './ScenarioGenerator.js';

// ═══════════════════════════════════════════════════════════════════════════
// VISUAL TEST CONFIG OVERRIDES
// ═══════════════════════════════════════════════════════════════════════════

// Some charts have TEST_CONFIGS with ES field names that don't match the
// synthetic test data generated by ScenarioGenerator. These overrides
// remap fields to match the generated test data.
const VISUAL_CONFIG_OVERRIDES = {
  // Categorical/bar charts
  bar: { xField: 'category', yField: 'value' },
  pie: { categoryField: 'category', valueField: 'value' },
  donut: { categoryField: 'category', valueField: 'value' },
  pareto: { categoryField: 'category', valueField: 'value' },
  treemap: { categoryField: 'category', valueField: 'value' },
  circle_packing: { categoryField: 'category', valueField: 'value' },
  radial: { categoryField: 'category', valueField: 'value' },

  // Time series charts
  line: { xField: 'date', yField: 'value', colorField: 'category' },
  area: { xField: 'date', yField: 'value', colorField: 'category' },
  rolling_average: { xField: 'date', yField: 'value' },
  sparkline: { xField: 'date', yField: 'value' },
  horizon: { xField: 'date', yField: 'value', colorField: 'category' },
  streamgraph: { xField: 'date', yField: 'value', colorField: 'category' },
  lasagna: { xField: 'date', yField: 'category', valueField: 'value' },
  dual_axis: { xField: 'date', yField: 'value1', y2Field: 'value2' },
  trellis_area: { xField: 'date', yField: 'value', facetField: 'category' },
  heatlane: { xField: 'date', yField: 'category', valueField: 'value' },

  // Scatter/point charts
  scatter: { xField: 'x_value', yField: 'y_value', colorField: 'category' },
  bubble: { xField: 'x_value', yField: 'y_value', sizeField: 'size_value', colorField: 'category' },
  marimekko: { xField: 'category', yField: 'value', colorField: 'subcategory' },

  // Heatmap charts
  heatmap: { xField: 'x_cat', yField: 'y_cat', valueField: 'value' },
  binned_heatmap: { xField: 'x_value', yField: 'y_value' },

  // Distribution charts
  histogram: { valueField: 'value' },
  boxplot: { categoryField: 'category', valueField: 'value' },
  density: { valueField: 'value', categoryField: 'category' },
  error_bars: { xField: 'category', yField: 'value' },
  violin: { categoryField: 'category', valueField: 'value' },

  // Flow charts
  sankey: { sourceField: 'source', targetField: 'target', valueField: 'value' },
  chord: { sourceField: 'source', targetField: 'target', valueField: 'value' },
  waterfall: { categoryField: 'category', valueField: 'value' },
  funnel: { stageField: 'stage', valueField: 'count' },

  // Specialized charts
  wordcloud: { wordField: 'word', frequencyField: 'frequency' },
  radar: { keyField: 'category', valueField: 'value' },
  gauge: { valueField: 'value' },
  bullet: { valueField: 'value', targetField: 'target' },

  // Complex charts
  ternary: { categoryField: 'category', aField: 'a_value', bField: 'b_value', cField: 'c_value' },
  comet: { categoryField: 'category', xStartField: 'x_start', yStartField: 'y_start', xEndField: 'x_end', yEndField: 'y_end' },
  population_pyramid: { categoryField: 'age_group', valueField: 'population', groupField: 'gender', leftGroup: 'Male', rightGroup: 'Female' }
};

// Helper to apply visual test config overrides
function getVisualTestConfig(chartType, baseConfig) {
  const overrides = VISUAL_CONFIG_OVERRIDES[chartType];
  if (overrides) {
    return { ...baseConfig, ...overrides };
  }
  return baseConfig;
}

// ═══════════════════════════════════════════════════════════════════════════
// SCENARIO SELECTION
// ═══════════════════════════════════════════════════════════════════════════

// Priority-based scenario selection for different test modes
const SCENARIO_PRESETS = {
  // Quick smoke test - just standard data
  quick: ['standard'],

  // Default - high priority scenarios (core 10)
  default: ['standard', 'minimal', 'single', 'negatives', 'zeros'],

  // Core scenarios (original 10)
  core: ['minimal', 'standard', 'large', 'empty', 'single', 'negatives', 'zeros', 'decimals', 'unicode', 'outliers'],

  // Extended scenarios (new 12)
  extended: ['very_large', 'all_same', 'long_labels', 'many_categories', 'missing_periods',
             'mixed_magnitude', 'nan_values', 'html_injection', 'circular_ref', 'rtl_text',
             'sparse', 'deep_hierarchy'],

  // Full test - all 22 scenarios
  full: Object.keys(SCENARIOS),

  // Edge cases only
  edge: ['empty', 'single', 'negatives', 'zeros', 'outliers', 'nan_values', 'sparse'],

  // Data volume testing
  volume: ['minimal', 'standard', 'large', 'many_categories'],

  // Display/rendering testing
  display: ['unicode', 'decimals', 'outliers', 'long_labels', 'rtl_text'],

  // Security testing
  security: ['html_injection', 'unicode'],

  // Numeric edge cases
  numeric: ['very_large', 'all_same', 'mixed_magnitude', 'nan_values', 'decimals', 'zeros', 'negatives'],

  // Structural edge cases
  structural: ['circular_ref', 'deep_hierarchy', 'missing_periods', 'sparse']
};

// ═══════════════════════════════════════════════════════════════════════════
// TEST RUNNER
// ═══════════════════════════════════════════════════════════════════════════

async function runTier3Tests(options = {}) {
  const {
    verbose = false,
    chartTypes = null,
    updateBaselines = false,
    scenarios = null,
    preset = 'default',
    parallel = false
  } = options;

  console.log('\n====================================================');
  console.log('  TIER 3: VISUAL REGRESSION (Multi-Scenario)');
  console.log('====================================================\n');

  const renderer = new HeadlessRenderer();
  const baselineManager = new BaselineManager();

  await baselineManager.ensureDirectories();

  // Determine which scenarios to run
  const scenariosToRun = scenarios || SCENARIO_PRESETS[preset] || SCENARIO_PRESETS.default;

  if (updateBaselines) {
    console.log('  Mode: UPDATE BASELINES\n');
  }

  console.log(`  Scenarios: ${scenariosToRun.join(', ')}\n`);

  const results = {
    total: 0,
    passed: 0,
    failed: 0,
    skipped: 0,
    baselineCreated: 0,
    errors: [],
    byScenario: {},
    byChart: {},
    details: []
  };

  // Initialize scenario tracking
  for (const scenario of scenariosToRun) {
    results.byScenario[scenario] = { passed: 0, failed: 0, skipped: 0 };
  }

  // Get chart types to test
  const typesToTest = chartTypes || Object.keys(TEST_CONFIGS);

  // Initialize chart tracking
  for (const chartType of typesToTest) {
    results.byChart[chartType] = { passed: 0, failed: 0, skipped: 0 };
  }

  const totalTests = typesToTest.length * scenariosToRun.length;
  console.log(`  Testing ${typesToTest.length} chart types × ${scenariosToRun.length} scenarios = ${totalTests} tests\n`);

  const startTime = Date.now();

  // Run tests
  for (const chartType of typesToTest) {
    const testConfig = TEST_CONFIGS[chartType];

    if (!testConfig) {
      if (verbose) {
        console.log(`  [SKIP] ${chartType} - no test config`);
      }
      for (const scenario of scenariosToRun) {
        results.skipped++;
        results.byScenario[scenario].skipped++;
        results.byChart[chartType].skipped++;
      }
      continue;
    }

    for (const scenario of scenariosToRun) {
      results.total++;
      const testId = `${chartType}:${scenario}`;

      try {
        // Get scenario-specific data
        const dataType = CHART_DATA_TYPES[chartType] || 'default';
        const mockData = generateScenarioData(dataType, scenario);

        // Skip empty scenario for charts that can't handle it gracefully
        if (scenario === 'empty' && mockData.length === 0) {
          // Test that empty data is handled (should not crash)
          try {
            const spec = chartRegistry.generate(chartType, testConfig.config, mockData);
            // If it generates without error, that's a pass for empty handling
            if (verbose) {
              console.log(`  [PASS] ${testId} - empty data handled`);
            }
            results.passed++;
            results.byScenario[scenario].passed++;
            results.byChart[chartType].passed++;
            results.details.push({
              chartType,
              scenario,
              status: 'pass',
              note: 'Empty data handled without crash'
            });
          } catch (emptyError) {
            // Some charts legitimately can't handle empty data
            if (verbose) {
              console.log(`  [SKIP] ${testId} - ${emptyError.message}`);
            }
            results.skipped++;
            results.byScenario[scenario].skipped++;
            results.byChart[chartType].skipped++;
            results.details.push({
              chartType,
              scenario,
              status: 'skipped',
              note: `Cannot handle empty: ${emptyError.message}`
            });
          }
          continue;
        }

        // Get scenario-adjusted config with visual test field overrides
        const baseConfig = getVisualTestConfig(chartType, testConfig.config);
        const config = getScenarioConfig(baseConfig, scenario);

        // Generate spec with scenario data
        const spec = chartRegistry.generate(chartType, config, mockData);

        // Render to PNG
        const png = await renderer.render(spec);

        // Validate content - check if chart actually rendered data
        const contentValidation = baselineManager.validateContent(png, chartType);

        if (updateBaselines) {
          // Update baseline mode
          await baselineManager.saveBaseline(chartType, scenario, png);
          results.passed++;
          results.byScenario[scenario].passed++;
          results.byChart[chartType].passed++;

          // Warn about empty charts even in update mode
          if (!contentValidation.valid) {
            console.log(`  [WARN] ${testId} - ${contentValidation.warning}`);
            if (!results.contentWarnings) results.contentWarnings = [];
            results.contentWarnings.push({
              chartType,
              scenario,
              ...contentValidation.analysis
            });
          } else if (verbose) {
            console.log(`  [UPDATE] ${testId}`);
          }
        } else {
          // Compare mode
          const comparison = await baselineManager.compareAndSave(chartType, scenario, png);

          if (comparison.status === 'baseline_created') {
            results.baselineCreated++;
            results.passed++;
            results.byScenario[scenario].passed++;
            results.byChart[chartType].passed++;
            if (verbose) {
              console.log(`  [NEW] ${testId} - baseline created`);
            }
          } else if (comparison.match) {
            results.passed++;
            results.byScenario[scenario].passed++;
            results.byChart[chartType].passed++;
            if (verbose) {
              console.log(`  [PASS] ${testId} (${comparison.diffPercent.toFixed(2)}% diff)`);
            }
          } else {
            results.failed++;
            results.byScenario[scenario].failed++;
            results.byChart[chartType].failed++;
            console.log(`  [FAIL] ${testId} - ${comparison.diffPercent.toFixed(2)}% different`);
            if (comparison.diffPath) {
              console.log(`         Diff: ${comparison.diffPath}`);
            }
          }

          results.details.push({
            chartType,
            scenario,
            ...comparison
          });
        }

      } catch (error) {
        results.failed++;
        results.byScenario[scenario].failed++;
        results.byChart[chartType].failed++;
        results.errors.push({ chartType, scenario, error: error.message });
        console.log(`  [ERROR] ${testId}: ${error.message}`);

        results.details.push({
          chartType,
          scenario,
          status: 'error',
          error: error.message
        });
      }
    }
  }

  const duration = Date.now() - startTime;

  // ═══════════════════════════════════════════════════════════════════════════
  // SUMMARY
  // ═══════════════════════════════════════════════════════════════════════════
  console.log('\n----------------------------------------------------');
  console.log(`  Results: ${results.passed}/${results.total} passed`);

  if (results.failed > 0) {
    console.log(`  Failed: ${results.failed}`);
  }
  if (results.baselineCreated > 0) {
    console.log(`  Baselines created: ${results.baselineCreated}`);
  }
  if (results.skipped > 0) {
    console.log(`  Skipped: ${results.skipped}`);
  }

  // Scenario breakdown
  console.log('\n  By Scenario:');
  for (const [scenario, stats] of Object.entries(results.byScenario)) {
    const total = stats.passed + stats.failed + stats.skipped;
    const icon = stats.failed > 0 ? '✗' : '✓';
    console.log(`    ${icon} ${scenario}: ${stats.passed}/${total - stats.skipped} passed`);
  }

  // Chart failures breakdown (only show if there are failures)
  if (results.failed > 0) {
    console.log('\n  Charts with failures:');
    for (const [chart, stats] of Object.entries(results.byChart)) {
      if (stats.failed > 0) {
        console.log(`    ✗ ${chart}: ${stats.failed} failures`);
      }
    }
  }

  // Content warnings - charts that render but have no data
  if (results.contentWarnings && results.contentWarnings.length > 0) {
    // Group by chart type
    const warningsByChart = {};
    for (const w of results.contentWarnings) {
      if (!warningsByChart[w.chartType]) {
        warningsByChart[w.chartType] = [];
      }
      warningsByChart[w.chartType].push(w);
    }

    console.log('\n  ⚠️  Charts with NO DATA rendered (generator bugs):');
    for (const [chart, warnings] of Object.entries(warningsByChart)) {
      const verdict = warnings[0].verdict;
      const dataPercent = warnings[0].dataPercent;
      console.log(`    ⚠ ${chart}: ${verdict} (${dataPercent}% data pixels)`);
    }
  }

  console.log(`\n  Duration: ${duration}ms`);
  console.log('----------------------------------------------------\n');

  return {
    ...results,
    duration,
    success: results.failed === 0
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// CLI SUPPORT
// ═══════════════════════════════════════════════════════════════════════════

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);

  // Parse arguments
  const verbose = args.includes('-v') || args.includes('--verbose');
  const updateBaselines = args.includes('--update') || args.includes('-u');

  // Chart filter
  const chartArg = args.find(a => a.startsWith('--chart='));
  const chartTypes = chartArg ? chartArg.split('=')[1].split(',') : null;

  // Scenario filter
  const scenarioArg = args.find(a => a.startsWith('--scenario='));
  const scenarios = scenarioArg ? scenarioArg.split('=')[1].split(',') : null;

  // Preset selection
  const presetArg = args.find(a => a.startsWith('--preset='));
  const preset = presetArg ? presetArg.split('=')[1] : 'default';

  // Help
  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Tier 3: Visual Regression Tests (Multi-Scenario)

Usage: node tests/visual-regression/run.js [options]

Options:
  -v, --verbose           Show detailed output
  -u, --update            Update baseline images
  --chart=<types>         Test specific chart types (comma-separated)
  --scenario=<scenarios>  Test specific scenarios (comma-separated)
  --preset=<preset>       Use scenario preset (quick|default|full|edge|volume|display)
  -h, --help              Show this help

Scenarios (10 total):
  minimal     - 1-2 data points (boundary conditions)
  standard    - Normal dataset (5-10 points)
  large       - Large dataset (50+ points)
  empty       - Empty arrays (null handling)
  single      - Single data point
  negatives   - Negative values (axis scaling)
  zeros       - Zero values (divide-by-zero, empty segments)
  decimals    - Floating point precision
  unicode     - Unicode/special characters
  outliers    - Extreme outliers (scale adaptation)

Presets:
  quick       - Just standard data (fastest)
  default     - standard, minimal, single, negatives, zeros
  full        - All 10 scenarios
  edge        - empty, single, negatives, zeros, outliers
  volume      - minimal, standard, large
  display     - unicode, decimals, outliers

Examples:
  node tests/visual-regression/run.js                          # Default scenarios
  node tests/visual-regression/run.js --preset=full            # All 10 scenarios
  node tests/visual-regression/run.js --preset=quick           # Quick smoke test
  node tests/visual-regression/run.js --scenario=outliers      # Single scenario
  node tests/visual-regression/run.js --chart=bar,line -v      # Specific charts
  node tests/visual-regression/run.js -u --preset=full         # Update all baselines

Environment Variables:
  VISUAL_DIFF_THRESHOLD   Pixel diff threshold (default: 0.01 = 1%)
`);
    process.exit(0);
  }

  runTier3Tests({ verbose, chartTypes, updateBaselines, scenarios, preset }).then(results => {
    process.exit(results.success ? 0 : 1);
  });
}

export { runTier3Tests, SCENARIO_PRESETS };
